<a href="https://colab.research.google.com/github/Atharv24-Atreus/Predictive-Analytics-Lab-/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Array creation using various methods
# 1D Array using np.array
array_1d = np.array([10, 20, 30, 40, 50])

# 2D Array using np.arange and reshaping
array_2d = np.arange(12).reshape(3, 4)

# 3D Array using np.linspace and reshaping
array_3d = np.linspace(1, 10, 24).reshape(2, 3, 4)

# Basic Operations: Indexing, Slicing, Reshaping, Concatenation
# Indexing
indexing_1d = array_1d[2]      # Element at index 2
indexing_2d = array_2d[1, 2]   # Element at row 1, column 2

# Slicing
slice_1d = array_1d[1:4]         # Slicing 1D array
slice_2d = array_2d[:, 1:3]      # Slicing columns 1 to 2 across all rows

# Reshaping arrays
reshaped_2d = array_2d.reshape(4, 3)  # Reshaping from 3x4 to 4x3

# Resizing arrays
resized_1d = np.resize(array_1d, (3, 2))  # Resize 1D array to 3x2

# Flattening arrays
flattened_3d = array_3d.flatten()

# Concatenating arrays
concat_1d = np.concatenate([array_1d, np.array([60, 70])])

# Investigating array attributes
shape_1d = array_1d.shape
size_2d = array_2d.size
dtype_3d = array_3d.dtype
ndim_2d = array_2d.ndim

# Print results
print("Array 1D:", array_1d)
print("Array 2D:", array_2d)
print("Array 3D:", array_3d)
print("Indexing 1D:", indexing_1d)
print("Indexing 2D:", indexing_2d)
print("Slice 1D:", slice_1d)
print("Slice 2D:", slice_2d)
print("Reshaped 2D:", reshaped_2d)
print("Resized 1D:", resized_1d)
print("Flattened 3D:", flattened_3d)
print("Concatenated 1D:", concat_1d)
print("Shape of 1D array:", shape_1d)
print("Size of 2D array:", size_2d)
print("Dtype of 3D array:", dtype_3d)
print("Ndim of 2D array:", ndim_2d)


Array 1D: [10 20 30 40 50]
Array 2D: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array 3D: [[[ 1.          1.39130435  1.7826087   2.17391304]
  [ 2.56521739  2.95652174  3.34782609  3.73913043]
  [ 4.13043478  4.52173913  4.91304348  5.30434783]]

 [[ 5.69565217  6.08695652  6.47826087  6.86956522]
  [ 7.26086957  7.65217391  8.04347826  8.43478261]
  [ 8.82608696  9.2173913   9.60869565 10.        ]]]
Indexing 1D: 30
Indexing 2D: 6
Slice 1D: [20 30 40]
Slice 2D: [[ 1  2]
 [ 5  6]
 [ 9 10]]
Reshaped 2D: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Resized 1D: [[10 20]
 [30 40]
 [50 10]]
Flattened 3D: [ 1.          1.39130435  1.7826087   2.17391304  2.56521739  2.95652174
  3.34782609  3.73913043  4.13043478  4.52173913  4.91304348  5.30434783
  5.69565217  6.08695652  6.47826087  6.86956522  7.26086957  7.65217391
  8.04347826  8.43478261  8.82608696  9.2173913   9.60869565 10.        ]
Concatenated 1D: [10 20 30 40 50 60 70]
Shape of 1D array: (5,)
Size of 2D array: 12
Dtype o

In [ ]:
import pandas as pd
import numpy as np

# Load the CSV file into a DataFrame
df = pd.read_csv('Book1.csv')

# Define the function to calculate probability
def prob(age_col, age_value, buy_col, buy_value):
    # Initialize the probability counter
    count = 0
    total = len(age_col)

    # Iterate through age and buy columns simultaneously
    for age, buy in zip(age_col, buy_col):
        if age == age_value and buy == buy_value:
            count += 1

    # Return the probability (count of matching / total)
    return count / total if total > 0 else 0

# Access the columns from the DataFrame
age = df['age']
income = df['income']
student = df['student']
credit_rating = df['credit rating']
buys_computer = df['Class: buys computer']

# Calculate probability of 'yes' and 'no' in the buys_computer column
prob_yes = buys_computer.value_counts().get('yes', 0) / len(buys_computer)
prob_no = buys_computer.value_counts().get('no', 0) / len(buys_computer)

# Calculate the probability of youth and yes for buying a computer
youth_yes_prob = prob(age, 'youth', buys_computer, 'yes')

# Print the results
print(f"Probability of 'youth' and 'yes': {youth_yes_prob}")
print(f"Probability of 'yes': {prob_yes}")
print(f"Probability of 'no': {prob_no}")


Probability of 'youth' and 'yes': 0.14285714285714285
Probability of 'yes': 0.6428571428571429
Probability of 'no': 0.35714285714285715
